# Example Docker Compose File
# You are expected to modify this to suit your own needs
version: '3'

services:
  server:
    image: ghcr.io/lolpants/satisfactory-dedicated:stable
    build: '.'
    ports:
      - 7777:7777/udp
      - 15000:15000/udp
      - 15777:15777/udp
    volumes:
      - ./data:/data:rw
