name: Docker Build
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  build-stable:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare
        id: prepare
        run: |
          IMAGE_NAME=satisfactory-dedicated

          GIT_REPO='https://github.com/${{ github.repository }}'
          DOCKER_USER=`echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]'`
          DOCKER_IMAGE=ghcr.io/$DOCKER_USER/$IMAGE_NAME
          BUILD_ID=`curl -s https://api.steamcmd.net/v1/info/1690800 | jq -r '.data["1690800"].depots.branches.public.buildid'`

          echo ::set-output name=git_repo::${GIT_REPO}
          echo ::set-output name=docker_user::${DOCKER_USER}
          echo ::set-output name=docker_image::${DOCKER_IMAGE}
          echo ::set-output name=build_id::${BUILD_ID}
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ steps.prepare.outputs.docker_user }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ (github.ref == 'refs/heads/master') || (contains(github.ref, 'refs/tags/') == true) }}
          tags: |
            ${{ steps.prepare.outputs.docker_image }}:${{ steps.prepare.outputs.build_id }}
            ${{ steps.prepare.outputs.docker_image }}:stable
          build-args: GIT_REPO=${{ steps.prepare.outputs.git_repo }}
          no-cache: true
  build-experimental:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare
        id: prepare
        run: |
          IMAGE_NAME=satisfactory-dedicated

          GIT_REPO='https://github.com/${{ github.repository }}'
          DOCKER_USER=`echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]'`
          DOCKER_IMAGE=ghcr.io/$DOCKER_USER/$IMAGE_NAME
          BUILD_ID=`curl -s https://api.steamcmd.net/v1/info/1690800 | jq -r '.data["1690800"].depots.branches.experimental.buildid'`

          echo ::set-output name=git_repo::${GIT_REPO}
          echo ::set-output name=docker_user::${DOCKER_USER}
          echo ::set-output name=docker_image::${DOCKER_IMAGE}
          echo ::set-output name=build_id::${BUILD_ID}
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ steps.prepare.outputs.docker_user }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ (github.ref == 'refs/heads/master') || (contains(github.ref, 'refs/tags/') == true) }}
          tags: |
            ${{ steps.prepare.outputs.docker_image }}:${{ steps.prepare.outputs.build_id }}
            ${{ steps.prepare.outputs.docker_image }}:experimental
          build-args: |
            GIT_REPO=${{ steps.prepare.outputs.git_repo }}
            SERVER_BRANCH="-beta experimental"
          no-cache: true
